import * as React from 'react';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  'use client';
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
